class_name CharacterMeshes
extends RefCounted
## The sculpted character meshes: heads per body, face and age, hair styles,
## beards and the skinned bodies per body, build and age. They are generated by
## the Python sculptor in tools/ and baked to .res by tools/bake_meshes.gd; this
## class loads them (cached) and makes their materials.
##
## Surfaces are named after their material: "skin", "eye", "hair", "lash".

const DIR := "res://actors/characters/meshes/"
## The head radius the heads and hair were sculpted at; models scale by head_r / BASE_HEAD_R.
const BASE_HEAD_R := 0.155

const SKIN_SHADER := preload("res://actors/characters/shaders/character_skin.gdshader")
const EYE_SHADER := preload("res://actors/characters/shaders/character_eye.gdshader")
const HAIR_SHADER := preload("res://actors/characters/shaders/character_hair.gdshader")

## Colour regions in a body mesh's UV2.x, matching character_skin.gdshader's region_* uniforms.
const REGIONS := ["skin", "top", "bottom", "boots", "leather", "trim", "inner", "tie"]

static var _cache := {}


static func head(body: String, face: String, age: int) -> ArrayMesh:
	return _load("heads/%s_%s_%s.res" % [body, face, "child" if age <= 0 else "adult"])


static func hair(style: String) -> ArrayMesh:
	return _load("hair/%s.res" % style)


static func beard(face: String, kind: String) -> ArrayMesh:
	return _load("beards/%s_%s.res" % [face, kind])


static func body(body_id: String, build: String, age: int) -> ArrayMesh:
	return _load("bodies/%s_%s_%s.res" % [body_id, build, "child" if age <= 0 else "adult"])


static func _load(rel: String) -> ArrayMesh:
	if _cache.has(rel):
		return _cache[rel]
	var path := DIR + rel
	var mesh: ArrayMesh = load(path) if ResourceLoader.exists(path) else null
	_cache[rel] = mesh
	return mesh


# --- Materials ---

static func skin_material(skin: Color, face := false, girl := false, child := false) -> ShaderMaterial:
	var m := ShaderMaterial.new()
	m.shader = SKIN_SHADER
	var regions: Array[Color] = []
	regions.resize(REGIONS.size())
	regions.fill(skin)
	set_regions(m, regions)
	m.set_shader_parameter("face_paint", 1.0 if face else 0.0)
	var lip := skin.darkened(0.25).lerp(Color("#b2524c"), 0.45 if girl else 0.25)
	m.set_shader_parameter("lip_color", lip)
	m.set_shader_parameter("lip_amount", 0.75 if girl else 0.5)
	m.set_shader_parameter("blush_color", skin.lerp(Color("#e0675c"), 0.6))
	m.set_shader_parameter("blush_amount", 0.4 if girl or child else 0.2)
	return m


## A body material: skin plus the outfit palette's top, bottom, boots and leather.
static func body_material(skin: Color, pal: Dictionary) -> ShaderMaterial:
	var m := skin_material(skin)
	var regions: Array[Color] = [
		skin, pal.get("top", Color.GRAY), pal.get("bottom", Color.DIM_GRAY), pal.get("boots", Color.SADDLE_BROWN),
		pal.get("leather", Color.SADDLE_BROWN), pal.get("metal", Color.GOLD),
		pal.get("inner", Color("#d9cfba")), pal.get("tie", Color("#7a3b2a")),
	]
	set_regions(m, regions)
	return m


## Sets a skin or body material's region colours, in REGIONS order.
static func set_regions(m: ShaderMaterial, colors: Array[Color]) -> void:
	for i in mini(colors.size(), REGIONS.size()):
		m.set_shader_parameter("region_" + REGIONS[i], colors[i])


static func eye_material(iris: Color) -> ShaderMaterial:
	var m := ShaderMaterial.new()
	m.shader = EYE_SHADER
	m.set_shader_parameter("iris_color", iris)
	return m


static func hair_material(color: Color) -> ShaderMaterial:
	var m := ShaderMaterial.new()
	m.shader = HAIR_SHADER
	m.set_shader_parameter("hair_color", color)
	return m


static func lash_material() -> StandardMaterial3D:
	var m := CharacterStyle.material(Color("#1c1210"), 0.0, 0.0)
	m.roughness = 1.0
	return m


# --- Loading the sculptor's output (used by tools/bake_meshes.gd) ---

## Reads an ACM1 file (see tools/meshio.py) into an ArrayMesh with one named surface per part.
static func from_acm(path: String) -> ArrayMesh:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		push_error("CharacterMeshes: can't open %s" % path)
		return null
	if f.get_buffer(4).get_string_from_ascii() != "ACM1":
		push_error("CharacterMeshes: %s is not an ACM1 file" % path)
		return null
	var header: Dictionary = JSON.parse_string(f.get_buffer(f.get_32()).get_string_from_utf8())
	var mesh := ArrayMesh.new()
	for s in header.surfaces:
		var nv := int(s.verts)
		var nt := int(s.tris)
		var pos := f.get_buffer(nv * 12).to_float32_array()
		var nrm := f.get_buffer(nv * 12).to_float32_array()
		var uv := f.get_buffer(nv * 8).to_float32_array()
		var uv2 := f.get_buffer(nv * 8).to_float32_array()
		var bones := f.get_buffer(nv * 16).to_int32_array()
		var weights := f.get_buffer(nv * 16).to_float32_array()
		var idx := f.get_buffer(nt * 12).to_int32_array()
		var arrays := []
		arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = _vec3(pos)
		arrays[Mesh.ARRAY_NORMAL] = _vec3(nrm)
		arrays[Mesh.ARRAY_TEX_UV] = _vec2(uv)
		arrays[Mesh.ARRAY_TEX_UV2] = _vec2(uv2)
		arrays[Mesh.ARRAY_INDEX] = idx
		var skinned: bool = header.meta.get("skinned", false)
		if skinned:
			arrays[Mesh.ARRAY_BONES] = bones
			arrays[Mesh.ARRAY_WEIGHTS] = weights
		mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		mesh.surface_set_name(mesh.get_surface_count() - 1, str(s.material))
	for key in header.meta:
		mesh.set_meta(key, header.meta[key])
	return mesh


static func _vec3(a: PackedFloat32Array) -> PackedVector3Array:
	var out := PackedVector3Array()
	out.resize(a.size() / 3)
	for i in out.size():
		out[i] = Vector3(a[i * 3], a[i * 3 + 1], a[i * 3 + 2])
	return out


static func _vec2(a: PackedFloat32Array) -> PackedVector2Array:
	var out := PackedVector2Array()
	out.resize(a.size() / 2)
	for i in out.size():
		out[i] = Vector2(a[i * 2], a[i * 2 + 1])
	return out
